[package]
name = "learn-rust"
version = "0.1.0"
authors = ["veaba <godpu@outlook.com>"]
edition = "2018"

[dependencies]
rand="0.3.14"
hyper="0.13"
tokio={version="0.2",features=["full"]}
regex="1.3.9"
resolv-conf="0.6.3"
serde_json="1.0.55"
serde="1.0.114"
rustc-serialize="0.3.24"
